<?php

namespace AppBundle\Repository;

/**
 * BookPropertiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookPropertiesRepository extends \Doctrine\ORM\EntityRepository
{
}
