<?php

namespace AppBundle\Repository;

/**
 * relationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relationRepository extends \Doctrine\ORM\EntityRepository
{
}
